Repository silx-kit/pyFAI, pull requests merged in 2018-12, with the labels that each got.

#1025 1021 preproc inlined
  pyFAI/ext/regrid_common.pxi
  pyFAI/ext/splitBBox.pyx
  pyFAI/ext/splitPixel.pyx
  pyFAI/test/test_split_pixel.py
Labels: ready to merge

#1027 Fix PySide2 compatibility
  pyFAI/gui/widgets/ElidedLabel.py
  pyFAI/gui/widgets/FileEdit.py
  pyFAI/gui/widgets/QuantityEdit.py
  pyFAI/gui/widgets/UnitLabel.py
Labels: ready to merge

#1028 Use data from frame (not from the file)
  pyFAI/app/integrate.py
Labels: bug

#993 831 variance in workers
  pyFAI/distortion.py
  pyFAI/ext/_distortion.pyx
  pyFAI/test/test_distortion.py
  pyFAI/worker.py
Labels: work in progress

#1031 1029 integation method
  pyFAI/azimuthalIntegrator.py
  pyFAI/distortion.py
  pyFAI/geometry.py
  pyFAI/method_registry.py
  pyFAI/test/test_azimuthal_integrator.py
  pyFAI/test/test_flat.py
  pyFAI/test/test_geometry.py
  pyFAI/test/test_openCL.py
  pyFAI/test/test_sparse.py
  pyFAI/test/test_utils.py
Labels: ready to merge

#1036 1035 future deprec
  pyFAI/azimuthalIntegrator.py
  pyFAI/test/test_saxs.py
  pyFAI/utils/decorators.py
  version.py
Labels: ready to merge

#1037 Warn if the discontinuity is in the azimuthal range
  pyFAI/azimuthalIntegrator.py
  pyFAI/geometry.py
Labels: ready to merge

#1040 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready to merge

#1038 0.17
  copyright
  doc/source/changelog.rst
  pyFAI/ext/splitPixelFullCSR.pyx
  pyFAI/ext/splitPixelFullLUT.pyx
  version.py
Labels: ready to merge

#1052 Fix semaphore api
  bootstrap.py
  pyFAI/diffmap.py
  pyFAI/gui/diffmap_widget.py
Labels: ready to merge

#1058 Ring displacment
  pyFAI/gui/calibration/GeometryTask.py
Labels: ready to merge

#1059 Fix linux copy-paste using middle mouse button
  pyFAI/gui/widgets/QuantityEdit.py
Labels: ready to merge

#1061 Avoid move peaklist scrollbar
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/gui/calibration/model/AbstractModel.py
  pyFAI/gui/calibration/model/PeakSelectionModel.py
Labels: ready to merge

#1062 Fix edf integration
  pyFAI/gui/IntegrationDialog.py
Labels: ready to merge

#1048 Deprecated comma list file
  pyFAI/azimuthalIntegrator.py
  pyFAI/detectors/_common.py
  pyFAI/gui/test/test_integrate_widget.py
  pyFAI/gui/widgets/WorkerConfigurator.py
  pyFAI/test/test_worker.py
  pyFAI/worker.py
Labels: ready to merge

#1073 Implement default/saxs constraints push buttons
  pyFAI/gui/calibration/GeometryTask.py
Labels: ready to merge

#1074 Robustness on MaskTask
  pyFAI/gui/calibration/MaskTask.py
Labels: ready to merge

#1080 974 nocheck kahan i386
  pyFAI/test/test_openCL.py
Labels: ready to merge
