Repository silx-kit/pyFAI, pull requests merged in 2018-07, with the labels that each got.

#855 848 kahan
  pyFAI/azimuthalIntegrator.py
  pyFAI/resources/openCL/kahan.cl
  pyFAI/test/test_openCL.py
Labels: ready to merge

#859 Cleanup
  pyFAI/spline.py
  pyFAI/test/test_spline.py
  run_tests.py
Labels: ready to merge

#854 Ocl profile
  pyFAI/opencl/processing.py
  pyFAI/opencl/sort.py
Labels: ready to merge

#864 Sparse builder
  .gitignore
  pyFAI/ext/_distortion.pyx
  pyFAI/ext/setup.py
  pyFAI/ext/sparse_builder.pxi
  pyFAI/ext/sparse_builder.pyx
  pyFAI/test/test_all.py
  pyFAI/test/test_sparse_builder.py
Labels: work in progress

#867 Use types comming from numpy to enforce the length
  pyFAI/ext/regrid_common.pxi
Labels: enhancement

#865 Implement to_lut to sparse builder
  pyFAI/ext/_distortion.pyx
  pyFAI/ext/sparse_builder.pxd
  pyFAI/ext/sparse_builder.pxi
  pyFAI/test/test_sparse_builder.py
Labels: ready to merge

#868 Deprecate legacy way of computing the mask
  pyFAI/azimuthalIntegrator.py
  pyFAI/test/test_azimuthal_integrator.py
Labels: ready to merge

#863 Provide detector configuration within the PONI file
  pyFAI/detectors/_adsc.py
  pyFAI/detectors/_common.py
  pyFAI/detectors/_dectris.py
  pyFAI/detectors/_esrf.py
  pyFAI/detectors/_imxpad.py
  pyFAI/detectors/_others.py
  pyFAI/detectors/_rayonix.py
  pyFAI/geometry.py
  pyFAI/test/test_detector.py
  pyFAI/test/test_geometry.py
Labels: ready to merge
