Repository silx-kit/pyFAI, pull requests merged in 2018-10, with the labels that each got.

#912 911 typo2
  ci/requirements_travis.txt
  pyFAI/ext/splitPixelFull.pyx
  pyFAI/ext/splitPixelFullCSR.pyx
  pyFAI/ext/splitPixelFullLUT.pyx
  pyFAI/ext/splitPixelFullLUT_double.pyx
Labels: bug

#919 Fix small issues
  doc/source/api/pyFAI.rst
  pyFAI/app/calib2.py
  pyFAI/ext/marchingsquares.pyx
  pyFAI/ext/setup.py
  pyFAI/gui/calibration/DetectorSelectorDrop.py
  pyFAI/gui/calibration/ExperimentTask.py
  pyFAI/gui/calibration/GeometryTask.py
  pyFAI/gui/calibration/MaskTask.py
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/test/test_all.py
  pyFAI/test/test_marchingsquares.py
Labels: ready to merge

#916 Opencl coef power
  ci/requirements_travis.txt
  doc/source/usage/tutorial/Variance/Variance.ipynb
  doc/source/usage/tutorial/index.rst
  pyFAI/azimuthalIntegrator.py
  pyFAI/containers.py
  pyFAI/ext/splitBBox.pyx
  pyFAI/ext/splitBBoxCSR.pyx
  pyFAI/ext/splitBBoxLUT.pyx
  pyFAI/ext/splitPixel.pyx
  pyFAI/opencl/azim_csr.py
  pyFAI/opencl/azim_lut.py
  pyFAI/opencl/ocl_azim_csr_dis.py
  pyFAI/resources/openCL/ocl_azim_CSR.cl
  pyFAI/resources/openCL/ocl_azim_LUT.cl
Labels: ready to merge

#913 882 error propagation without splitting
  pyFAI/azimuthalIntegrator.py
Labels: enhancement, ready to merge

#923 298 opencl from silx
  pyFAI/azimuthalIntegrator.py
  pyFAI/opencl/OCLFullSplit.py
  pyFAI/opencl/__init__.py
  pyFAI/opencl/azim_csr.py
  pyFAI/opencl/azim_hist.py
  pyFAI/opencl/azim_lut.py
  pyFAI/opencl/common.py
  pyFAI/opencl/ocl_hist_pixelsplit.py
  pyFAI/opencl/preproc.py
  pyFAI/opencl/processing.py
  pyFAI/opencl/sort.py
  pyFAI/opencl/test/test_addition.py
  pyFAI/opencl/utils.py
  pyFAI/test/test_openCL.py
  pyFAI/test/test_preproc.py
  pyFAI/utils/__init__.py
Labels: ready to merge

#921 Polishing calib2
  pyFAI/gui/calibration/AbstractCalibrationTask.py
  pyFAI/gui/calibration/CalibrationWindow.py
  pyFAI/gui/calibration/ExperimentTask.py
  pyFAI/gui/calibration/GeometryTask.py
  pyFAI/gui/calibration/IntegrationTask.py
  pyFAI/gui/calibration/MaskTask.py
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/gui/widgets/QuantityLabel.py
  pyFAI/resources/gui/calibration-main.ui
  pyFAI/resources/gui/icons/layer-warning.png
  pyFAI/resources/gui/icons/layer-warning.svg
  pyFAI/resources/gui/icons/task-cake.png
  pyFAI/resources/gui/icons/task-cake.svg
  pyFAI/resources/gui/icons/task-fit-geometry.png
  pyFAI/resources/gui/icons/task-fit-geometry.svg
  pyFAI/resources/gui/icons/task-identify-rings.png
  pyFAI/resources/gui/icons/task-identify-rings.svg
  pyFAI/resources/gui/icons/task-mask.png
  pyFAI/resources/gui/icons/task-mask.svg
  pyFAI/resources/gui/icons/task-settings.png
  pyFAI/resources/gui/icons/task-settings.svg
  pyFAI/resources/gui/icons/warning.png
  pyFAI/resources/gui/icons/warning.svg
Labels: ready to merge

#922 Add naive tests
  pyFAI/gui/test/__init__.py
  pyFAI/gui/test/test_calibration.py
Labels: ready to merge

#925 fix the test coverage part in order to release v0.16
  pyFAI/test/test_utils.py
  run_tests.py
Labels: ready to merge

#931 930 help2man
  pyFAI/app/average.py
  pyFAI/app/benchmark.py
  pyFAI/app/calib.py
  pyFAI/app/calib2.py
  pyFAI/app/check_calib.py
  pyFAI/app/detector2nexus.py
  pyFAI/app/diff_map.py
  pyFAI/app/diff_tomo.py
  pyFAI/app/drawmask.py
  pyFAI/app/eiger_mask.py
  pyFAI/app/integrate.py
  pyFAI/app/mx_calibrate.py
  pyFAI/app/recalib.py
  pyFAI/app/saxs.py
  pyFAI/app/waxs.py
  pyFAI/diffmap.py
  pyFAI/gui/cli_calibration.py
  pyFAI/test/test_ocl_sort.py
  pyFAI/test/utilstest.py
  pyFAI/third_party/_local/argparse.py
  pyFAI/third_party/argparse.py
  setup.py
Labels: ready to merge

#935 Fix bunch of small issues
  pyFAI/app/calib2.py
  pyFAI/detectors/_imxpad.py
  pyFAI/detectors/_others.py
  pyFAI/detectors/_rayonix.py
  pyFAI/gui/calibration/CalibrationContext.py
  pyFAI/gui/calibration/DetectorSelectorDrop.py
  pyFAI/gui/calibration/ExperimentTask.py
  pyFAI/gui/calibration/GeometryTask.py
  pyFAI/gui/calibration/IntegrationTask.py
  pyFAI/gui/calibration/MaskTask.py
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/gui/calibration/RingCalibration.py
  pyFAI/gui/utils/timeutils.py
  pyFAI/gui/widgets/CalibrantSelector.py
  pyFAI/gui/widgets/DetectorLabel.py
  pyFAI/gui/widgets/DetectorManufacturer.py
  pyFAI/gui/widgets/DetectorModel.py
  pyFAI/resources/gui/calibration-main.ui
  pyFAI/resources/gui/calibration-peakpicking.ui
  pyFAI/resources/gui/detector-selection-drop.ui
  pyFAI/resources/gui/icons/task-cake.png
  pyFAI/resources/gui/icons/task-cake.svg
  pyFAI/resources/gui/icons/task-fit-geometry.png
  pyFAI/resources/gui/icons/task-fit-geometry.svg
  pyFAI/resources/gui/icons/task-identify-rings.png
  pyFAI/resources/gui/icons/task-identify-rings.svg
  pyFAI/resources/gui/icons/task-mask.png
  pyFAI/resources/gui/icons/task-mask.svg
  pyFAI/resources/gui/icons/task-settings.png
  pyFAI/resources/gui/icons/task-settings.svg
Labels: ready to merge

#938 Massif handles masked values.
  pyFAI/massif.py
  pyFAI/test/test_all.py
  pyFAI/test/test_massif.py
Labels: ready to merge

#940 Update tutorial on variance propagation
  doc/source/usage/tutorial/Variance/Variance.ipynb
Labels: ready to merge

#941 Fix file license
  pyFAI/test/test_pickle.py
Labels: ready to merge

#939 Features a full ring picking on calib2
  pyFAI/gui/calibration/GeometryTask.py
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/resources/gui/calibration-peakpicking.ui
  pyFAI/resources/gui/icons/search-full-ring.png
  pyFAI/resources/gui/icons/search-full-ring.svg
Labels: ready to merge

#946 Improve filedialog filters
  pyFAI/gui/calibration/DetectorSelectorDrop.py
  pyFAI/gui/calibration/ExperimentTask.py
  pyFAI/gui/calibration/IntegrationTask.py
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/gui/utils/FilterBuilder.py
Labels: ready to merge

#949 Doc calib2
  doc/source/usage/cookbook/calib-cli/calibrate.rst
  doc/source/usage/cookbook/calib-cli/fabio_viewer.png
  doc/source/usage/cookbook/calib-cli/pyFAI-calib_1.png
  doc/source/usage/cookbook/calib-cli/pyFAI-calib_2.png
  doc/source/usage/cookbook/calib-cli/pyFAI-calib_3.png
  doc/source/usage/cookbook/calib-cli/pyFAI-calib_4.png
  doc/source/usage/cookbook/calib-cli/pyFAI-calib_5.png
  doc/source/usage/cookbook/calib-gui/0_startup.png
  doc/source/usage/cookbook/calib-gui/1_experiment.png
  doc/source/usage/cookbook/calib-gui/2_mask.png
  doc/source/usage/cookbook/calib-gui/3_extract.png
  doc/source/usage/cookbook/calib-gui/3_picking.png
  doc/source/usage/cookbook/calib-gui/4_geometry.png
  doc/source/usage/cookbook/calib-gui/5_cake.png
  doc/source/usage/cookbook/calib-gui/index.rst
  doc/source/usage/cookbook/index.rst
  pyFAI/resources/gui/calibration-peakpicking.ui
Labels: ready to merge

#945 Cython coef power
  package/debian8/control
  package/debian8/pyfai-doc.doc-base
  package/debian8/rules
  package/debian9/control
  package/debian9/pyfai-doc.doc-base
  package/debian9/rules
  pyFAI/app/diff_map.py
  pyFAI/ext/splitBBoxCSR.pyx
  pyFAI/ext/splitPixel.pyx
  pyFAI/ext/splitPixelFullCSR.pyx
  pyFAI/gui/calibration/RingCalibration.py
  pyFAI/gui/integrate_widget.py
  pyFAI/test/test_split_pixel.py
Labels: ready to merge

#952 Typo
  pyFAI/resources/gui/calibration-peakpicking.ui
Labels: ready to merge

#967 Merge peakpicker actions
  pyFAI/gui/calibration/PeakPickingTask.py
  pyFAI/gui/calibration/helper/MarkerManager.py
  pyFAI/gui/calibration/model/PeakModel.py
  pyFAI/gui/calibration/model/PeakSelectionModel.py
  pyFAI/gui/utils/validators.py
  pyFAI/resources/gui/calibration-peakpicking.ui
Labels: ready to merge

#977 Fix validators
  pyFAI/gui/test/__init__.py
  pyFAI/gui/utils/setup.py
  pyFAI/gui/utils/test/__init__.py
  pyFAI/gui/utils/test/test_validators.py
  pyFAI/gui/utils/validators.py
Labels: ready to merge
