Repository silx-kit/pyFAI, pull requests merged in 2021-01, with the labels that each got.

#1419 Doc
  README.rst
  ci/requirements_rtd.txt
  doc/source/api/app/index.rst
  doc/source/api/gui/index.rst
  doc/source/api/io/index.rst
  doc/source/api/modules.rst
  doc/source/api/pyFAI.rst
  doc/source/calibration.rst
  doc/source/changelog.rst
  doc/source/design/ai.rst
  doc/source/design/index.rst
  doc/source/detector.rst
  doc/source/ecosystem.rst
  doc/source/geometry.rst
  doc/source/glossary.rst
  doc/source/img/logo.odg
  doc/source/img/logo.svg
  doc/source/img/overview.odg
  doc/source/img/overview.png
  doc/source/index.rst
  doc/source/man/scripts.rst
  doc/source/operations/index.rst
  doc/source/operations/linux.rst
  doc/source/operations/macosx.rst
  doc/source/operations/windows.rst
  doc/source/project.rst
  doc/source/publications.rst
  doc/source/pyFAI.rst
  doc/source/usage/cookbook/calib-gui/index.rst
  doc/source/usage/cookbook/index.rst
  doc/source/usage/index.rst
  doc/source/usage/tutorial/Introduction/introduction.ipynb
  doc/source/usage/tutorial/index.rst
  pyFAI/test/test_bug_regression.py
  requirements.txt
Labels: doc

#1437 Deprecation:
  pyFAI/app/benchmark.py
  pyFAI/app/calib.py
  pyFAI/app/check_calib.py
  pyFAI/app/diff_tomo.py
  pyFAI/app/integrate.py
  pyFAI/app/mx_calibrate.py
  pyFAI/app/recalib.py
  pyFAI/average.py
  pyFAI/azimuthalIntegrator.py
  pyFAI/benchmark/__init__.py
  pyFAI/control_points.py
  pyFAI/detectors/_common.py
  pyFAI/diffmap.py
  pyFAI/distortion.py
  pyFAI/ext/_bispev.pyx
  pyFAI/ext/_blob.pyx
  pyFAI/ext/_convolution.pyx
  pyFAI/ext/_distortion.pyx
  pyFAI/ext/_geometry.pyx
  pyFAI/geometry.py
  pyFAI/gui/cli_calibration.py
  pyFAI/gui/peak_picker.py
  pyFAI/gui/tasks/ExperimentTask.py
  pyFAI/gui/tasks/PeakPickingTask.py
  pyFAI/gui/utils/units.py
  pyFAI/io/__init__.py
  pyFAI/io/integration_config.py
  pyFAI/io/ponifile.py
  pyFAI/massif.py
  pyFAI/opencl/azim_hist.py
  pyFAI/resources/openCL/ocl_azim_kernel2d_2.cl
  pyFAI/resources/openCL/ocl_azim_kernel_2.cl
  pyFAI/test/test_azimuthal_integrator.py
  pyFAI/test/test_bispev.py
  pyFAI/test/test_histogram.py
  pyFAI/test/test_mask.py
  pyFAI/test/test_openCL.py
  pyFAI/test/test_saxs.py
  pyFAI/test/utilstest.py
  pyFAI/third_party/_local/enum.py
  pyFAI/third_party/_local/six.py
  pyFAI/third_party/copyright
  pyFAI/third_party/enum.py
  pyFAI/third_party/six.py
  pyFAI/units.py
  pyFAI/utils/__init__.py
  pyFAI/utils/decorators.py
  pyFAI/worker.py
  run_tests.py
  sandbox/JF16_geometry.ipynb
  setup.py
Labels: ready to merge

#1244 Update binder environment
  binder/index.ipynb
  binder/index_template.ipynb
  binder/postBuild
Labels: ready to merge

#1443 Cleanup cython
  pyFAI/ext/_convolution.pyx
  pyFAI/ext/_geometry.pyx
  pyFAI/ext/sparse_builder.pyx
  pyFAI/ext/splitBBoxLUT.pyx
Labels: ready to merge

#1452 Dynamic worgroup
  pyFAI/app/benchmark.py
  pyFAI/azimuthalIntegrator.py
  pyFAI/benchmark/__init__.py
  pyFAI/calibrant.py
  pyFAI/method_registry.py
  pyFAI/opencl/OCLFullSplit.py
  pyFAI/opencl/azim_csr.py
  pyFAI/opencl/ocl_hist_pixelsplit.py
  pyFAI/opencl/peak_finder.py
  pyFAI/opencl/test/__init__.py
  pyFAI/opencl/test/test_ocl_sort.py
  pyFAI/opencl/test/test_openCL.py
  pyFAI/resources/openCL/ocl_azim_CSR.cl
  pyFAI/resources/openCL/peak_finder.cl
  pyFAI/test/test_all.py
Labels: enhancement

#1464 1463 benchmarking
  doc/source/img/benchmark_0.20.png
  doc/source/img/benchmark_0.20.svg
  pyFAI/benchmark/__init__.py
Labels: ready to merge
