Repository silx-kit/pyFAI, pull requests merged in 2024-01, with the labels that each got.

#2028 support pathlib.Path
  doc/source/changelog.rst
  src/pyFAI/ext/histogram.pyx
  src/pyFAI/io/ponifile.py
  src/pyFAI/test/test_io.py
Labels: ready to merge, easy

#2030 Support Xrdml
  doc/source/changelog.rst
  src/pyFAI/azimuthalIntegrator.py
  src/pyFAI/io/__init__.py
  src/pyFAI/io/meson.build
  src/pyFAI/io/xrdml.py
  src/pyFAI/test/test_io.py
Labels: ready to merge

#2032 Register the number of pixel corners
  doc/source/changelog.rst
  src/pyFAI/detectors/__init__.py
  src/pyFAI/detectors/_adsc.py
  src/pyFAI/detectors/_common.py
  src/pyFAI/detectors/_hexagonal.py
  src/pyFAI/io/ponifile.py
  src/pyFAI/test/test_detector.py
Labels: ready to merge

#2042 minor issues in tutorials
  doc/source/usage/tutorial/Detector/Pilatus_Calibration/Pilatus_ID15.ipynb
  doc/source/usage/tutorial/Separation/Peakfinder8.ipynb
  doc/source/usage/tutorial/Soleil/soleil.py
  doc/source/usage/tutorial/Variance/Variance.ipynb
Labels: ready to merge

#2043 2024.01
  doc/source/coverage.rst
  doc/source/img/benchmark_2024.01.svg
  doc/source/man/pyFAI-benchmark.rst
  doc/source/operations/index.rst
  doc/source/operations/linux.rst
  doc/source/performance.rst
  pyproject.toml
  version.py
Labels: ready to merge

#2046 address deprecation warning
  src/pyFAI/gui/tasks/ExperimentTask.py
  src/pyFAI/gui/tasks/GeometryTask.py
  src/pyFAI/gui/tasks/IntegrationTask.py
  src/pyFAI/gui/tasks/MaskTask.py
  src/pyFAI/gui/tasks/PeakPickingTask.py
Labels: ready to merge

#2052 reset thread-pool
  src/pyFAI/multi_geometry.py
Labels: ready to merge

#2054 2053 lut uncertainties
  src/pyFAI/ext/CSR_common.pxi
  src/pyFAI/ext/LUT_common.pxi
  src/pyFAI/test/test_bug_regression.py
Labels: ready to merge

#2063 Use the dynamic mask in the calibration GUI
  doc/source/changelog.rst
  src/pyFAI/gui/model/ExperimentSettingsModel.py
Labels: gui, ready to merge

#2064 Explicitely close the dialog to prevent crash
  src/pyFAI/gui/widgets/LoadImageToolButton.py
Labels: gui, ready to merge
