Repository silx-kit/pyFAI, pull requests merged in 2024-04, with the labels that each got.

#2114 2113 diffmap variables
  src/pyFAI/app/diff_tomo.py
  src/pyFAI/diffmap.py
  src/pyFAI/gui/diffmap_widget.py
Labels: ready to merge

#2118 deprecation warning in set_config
  src/pyFAI/diffmap.py
  src/pyFAI/gui/diffmap_widget.py
Labels: ready to merge

#2131 additional possibilities in diffmap
  src/pyFAI/diffmap.py
Labels: ready to merge

#2133 2129 pilx multiselection , click / double-click approach
  src/pyFAI/gui/pilx/MainWindow.py
  src/pyFAI/gui/pilx/widgets/ImagePlotWidget.py
  src/pyFAI/gui/pilx/widgets/MapPlotContextMenu.py
  src/pyFAI/gui/pilx/widgets/MapPlotWidget.py
  src/pyFAI/gui/pilx/widgets/meson.build
Labels: work in progress, proposal

#2141 Rebin the mask as needed
  src/pyFAI/detectors/_common.py
  src/pyFAI/test/test_detector.py
Labels: ready to merge

#2134 parser should not mangle method (too much)
  src/pyFAI/azimuthalIntegrator.py
  src/pyFAI/diffmap.py
  src/pyFAI/io/integration_config.py
  src/pyFAI/load_integrators.py
  src/pyFAI/opencl/__init__.py
  src/pyFAI/test/test_integrate_config.py
  version.py
Labels: quality, ready to merge

#2146 Implement and expose unweighted average for 1D integration
  src/pyFAI/azimuthalIntegrator.py
  src/pyFAI/containers.py
  src/pyFAI/engines/CSC_engine.py
  src/pyFAI/engines/CSR_engine.py
  src/pyFAI/engines/histogram_engine.py
  src/pyFAI/engines/preproc.py
  src/pyFAI/ext/CSC_common.pxi
  src/pyFAI/ext/CSR_common.pxi
  src/pyFAI/ext/LUT_common.pxi
  src/pyFAI/ext/histogram.pyx
  src/pyFAI/ext/preproc.pyx
  src/pyFAI/ext/regrid_common.pxi
  src/pyFAI/ext/splitBBox.pyx
  src/pyFAI/ext/splitPixel.pyx
  src/pyFAI/io/nexus.py
  src/pyFAI/opencl/azim_csr.py
  src/pyFAI/opencl/azim_hist.py
  src/pyFAI/opencl/azim_lut.py
  src/pyFAI/opencl/ocl_hist_pixelsplit.py
  src/pyFAI/opencl/preproc.py
  src/pyFAI/resources/openCL/preprocess.cl
  src/pyFAI/test/test_io.py
Labels: ready to merge

#2147 Improve benchmarks:
  src/pyFAI/benchmark/__init__.py
Labels: ready to merge

#2153 full-split CSC matrix has wrong size when last line of detector is masked out
  src/pyFAI/ext/splitPixelFullCSC.pyx
  src/pyFAI/ext/splitpixel_common.pyx
  src/pyFAI/test/test_bug_regression.py
Labels: ready to merge

#2143 2127 flat, dark, background in pyFAI-calib2 [PROPOSAL]
  src/pyFAI/app/calib2.py
  src/pyFAI/gui/model/ExperimentSettingsModel.py
  src/pyFAI/gui/model/PreProcessedImageModel.py
  src/pyFAI/gui/model/meson.build
  src/pyFAI/gui/tasks/ExperimentTask.py
  src/pyFAI/gui/tasks/GeometryTask.py
  src/pyFAI/gui/tasks/IntegrationTask.py
  src/pyFAI/gui/tasks/PeakPickingTask.py
  src/pyFAI/resources/gui/calibration-experiment.ui
Labels: ready to merge
