Repository silx-kit/pyFAI, pull requests merged in 2024-08, with the labels that each got.

#2240 [pyFAI-calib2] new feature: save .json file
  src/pyFAI/gui/model/ExperimentSettingsModel.py
  src/pyFAI/gui/tasks/IntegrationTask.py
  src/pyFAI/resources/gui/calibration-result.ui
Labels: enhancement, ready to merge, proposal

#2239 This pull request addresses issue #2221
  src/pyFAI/average.py
Labels: proposal

#2248 Remove deprecated code
  src/pyFAI/ext/sparse_utils.pyx
  src/pyFAI/test/test_sparse.py
Labels: ready to merge

#2249 Worker new version 4
  src/pyFAI/diffmap.py
  src/pyFAI/gui/pilx/utils.py
  src/pyFAI/gui/widgets/WorkerConfigurator.py
  src/pyFAI/io/integration_config.py
  src/pyFAI/io/ponifile.py
  src/pyFAI/test/test_worker.py
  src/pyFAI/worker.py
Labels: ready to merge

#2256 [GIWAXS] force split_pixel=no
  src/pyFAI/azimuthalIntegrator.py
Labels: ready to merge

#2252 get_config_from_poni
  src/pyFAI/io/integration_config.py
  src/pyFAI/io/ponifile.py
Labels: ready to merge
