Repository silx-kit/pyFAI, pull requests merged in 2024-11, with the labels that each got.

#2322 Update API doc using `pyFAI.integrator`
  doc/source/api/pyFAI.rst
Labels: doc

#2317 Fix deprecation warning
  src/pyFAI/test/test_method_registry.py
Labels: ready to merge, easy

#2318 Include fiber integrator into test suite
  src/pyFAI/test/test_all.py
  src/pyFAI/test/test_fiber_integrator.py
Labels: bug, ready to merge

#2327 Offer the selection of individual OpenCL devices
  CITATION.cff
  src/pyFAI/app/benchmark.py
Labels: ready to merge

#2319 Implement OpenCL collective scan functions
  src/pyFAI/opencl/test/test_collective.py
  src/pyFAI/resources/openCL/collective/comb_sort.cl
  src/pyFAI/resources/openCL/collective/scan.cl
Labels: ready to merge

#2324 lighter FiberIntegrator class
  src/pyFAI/integrator/fiber.py
  src/pyFAI/test/test_fiber_integrator.py
  src/pyFAI/units.py
Labels: ready to merge

#2332 Test for OpenCL Comb-Sort
  src/pyFAI/opencl/test/test_collective.py
  src/pyFAI/resources/openCL/collective/comb_sort.cl
  src/pyFAI/resources/openCL/collective/reduction.cl
Labels: ready to merge

#2334 Python implementation of medfilt_ng
  src/pyFAI/engines/CSR_engine.py
  src/pyFAI/test/meson.build
  src/pyFAI/test/test_all.py
  src/pyFAI/test/test_medfilt_engine.py
Labels: ready to merge

#2336 simplify fiber integrator
  src/pyFAI/integrator/fiber.py
Labels: ready to merge
