Repository silx-kit/pyFAI, pull requests merged in 2024-03, with the labels that each got.

#2081 Improve performances for ring extraction
  doc/source/usage/tutorial/Goniometer/Fit_wavelength/fit_energy.ipynb
  doc/source/usage/tutorial/Goniometer/Rotation-Pilatus100k/Multi120_Pilatus100k.ipynb
  doc/source/usage/tutorial/Goniometer/Rotation-Pilatus100k/ROBL_v1.json
  doc/source/usage/tutorial/Goniometer/Rotation-Pilatus100k/ROBL_v2.json
  doc/source/usage/tutorial/Goniometer/Rotation-XPADS540/D2AM-15.ipynb
  doc/source/usage/tutorial/Goniometer/Translation-Pilatus6M/ID29.json
  doc/source/usage/tutorial/Goniometer/Translation-Pilatus6M/TTcalibration.ipynb
  src/pyFAI/ext/invert_geometry.pyx
  src/pyFAI/ext/mathutil.pyx
  src/pyFAI/ext/meson.build
  src/pyFAI/goniometer.py
  src/pyFAI/massif.py
  src/pyFAI/test/test_utils_mathutil.py
  src/pyFAI/utils/mathutil.py
Labels: ready to merge, performance

#2080 Move ImageD11 conversion to an extra sub-module
  ci/requirements_gh.txt
  src/pyFAI/detectors/_common.py
  src/pyFAI/geometry/core.py
  src/pyFAI/geometry/imaged11.py
  src/pyFAI/geometry/meson.build
  src/pyFAI/test/test_export.py
  src/pyFAI/units.py
Labels: enhancement

#2089 make worker.shape a property using the detector from the azimuthal integrator
  src/pyFAI/test/test_worker.py
  src/pyFAI/worker.py
Labels: ready to merge

#2096 Refine wavelength
  src/pyFAI/geometryRefinement.py
Labels: ready to merge

#2097 Pilx
  pyproject.toml
  setup.cfg
  src/pyFAI/app/meson.build
  src/pyFAI/app/pilx.py
  src/pyFAI/diffmap.py
  src/pyFAI/gui/diffmap_widget.py
  src/pyFAI/gui/meson.build
  src/pyFAI/gui/pilx/HorizontalRangeROI.py
  src/pyFAI/gui/pilx/MainWindow.py
  src/pyFAI/gui/pilx/__init__.py
  src/pyFAI/gui/pilx/meson.build
  src/pyFAI/gui/pilx/models.py
  src/pyFAI/gui/pilx/utils.py
  src/pyFAI/gui/pilx/widgets/DiffractionImagePlotWidget.py
  src/pyFAI/gui/pilx/widgets/ImagePlotWidget.py
  src/pyFAI/gui/pilx/widgets/IntegratedPatternPlotWidget.py
  src/pyFAI/gui/pilx/widgets/MapPlotWidget.py
  src/pyFAI/gui/pilx/widgets/OpenAxisDatasetAction.py
  src/pyFAI/gui/pilx/widgets/RoiModeAction.py
  src/pyFAI/gui/pilx/widgets/RoiRangeWidget.py
  src/pyFAI/gui/pilx/widgets/TitleWidget.py
  src/pyFAI/gui/pilx/widgets/__init__.py
  src/pyFAI/gui/pilx/widgets/meson.build
  src/pyFAI/opencl/__init__.py
Labels: question, gui, ready to merge

#2112 remove RuntimeError
  src/pyFAI/gui/diffmap_widget.py
Labels: ready to merge
