Repository silx-kit/pyFAI, pull requests merged in 2025-02, with the labels that each got.

#2424 [pilx] fix single pixel map
  src/pyFAI/gui/pilx/widgets/MapPlotWidget.py
Labels: ready to merge

#2423 Ensure max_shape is a tuple (not a list)
  src/pyFAI/detectors/_common.py
  src/pyFAI/test/test_worker.py
Labels: ready to merge

#2426 Store objects in WorkerConfig rather than nested dictionaries
  src/pyFAI/app/integrate.py
  src/pyFAI/detectors/_common.py
  src/pyFAI/gui/IntegrationDialog.py
  src/pyFAI/gui/dialog/IntegrationMethodDialog.py
  src/pyFAI/gui/widgets/WorkerConfigurator.py
  src/pyFAI/io/__init__.py
  src/pyFAI/io/integration_config.py
  src/pyFAI/io/ponifile.py
  src/pyFAI/test/test_integrate_app.py
  src/pyFAI/test/test_integrate_config.py
  src/pyFAI/units.py
  src/pyFAI/worker.py
Labels: ready to merge

#2429 Simplify by using dataclasses in calib2
  src/pyFAI/gui/tasks/IntegrationTask.py
Labels: gui, ready to merge

#2425 Better dict-like interface for `WorkerConfig` dataclass
  src/pyFAI/io/integration_config.py
Labels: ready to merge

#2438 Auto guess the binning from the reading of the first image
  src/pyFAI/app/integrate.py
  src/pyFAI/worker.py
Labels: enhancement

#2441 fake data soft condition
  src/pyFAI/calibrant.py
Labels: ready to merge

#2419 Diffmap
  src/pyFAI/app/integrate.py
  src/pyFAI/diffmap.py
  src/pyFAI/geometry/core.py
  src/pyFAI/gui/diffmap_widget.py
  src/pyFAI/gui/pilx/MainWindow.py
  src/pyFAI/gui/widgets/WorkerConfigurator.py
  src/pyFAI/integrator/azimuthal.py
  src/pyFAI/integrator/common.py
  src/pyFAI/io/__init__.py
  src/pyFAI/io/integration_config.py
  src/pyFAI/io/ponifile.py
  src/pyFAI/test/test_integrate_app.py
  src/pyFAI/test/test_utils_mathutil.py
  src/pyFAI/test/test_worker.py
  src/pyFAI/utils/mathutil.py
  src/pyFAI/worker.py
Labels: ready to merge

#2446 pilx binning
  src/pyFAI/gui/pilx/utils.py
Labels: ready to merge

#2453 Ensure the 2 opened file in the Nexus class are actually closed when the object is deleted
  src/pyFAI/io/nexus.py
Labels: ready to merge

#2450 [pilx] use dynamic masking for diffraction images
  src/pyFAI/gui/pilx/MainWindow.py
Labels: gui, ready to merge
