Repository silx-kit/pyFAI, pull requests merged in 2025-01, with the labels that each got.

#2374 rebin in 1d from 2d data
  ci/requirements_gh.txt
  doc/source/changelog.rst
  src/pyFAI/containers.py
  src/pyFAI/integrator/azimuthal.py
  src/pyFAI/test/meson.build
  src/pyFAI/test/test_all.py
  src/pyFAI/test/test_containers.py
Labels: ready to merge

#2362 Handle diffmap mask as URL
  doc/source/publications.rst
  src/pyFAI/diffmap.py
  src/pyFAI/io/image.py
Labels: ready to merge

#2366 Easy promotion
  src/pyFAI/geometry/core.py
  src/pyFAI/test/test_geometry.py
Labels: ready to merge, doc

#2377 fiber repr
  src/pyFAI/integrator/fiber.py
Labels: ready to merge

#2378 Sample orientations exif
  sandbox/test_grazingincidence.py
  src/pyFAI/integrator/fiber.py
  src/pyFAI/test/test_fiber_integrator.py
  src/pyFAI/units.py
Labels: ready to merge

#2376 silent deprecation warnings in tests
  src/pyFAI/geometry/core.py
  src/pyFAI/spline.py
  src/pyFAI/test/test_azimuthal_integrator.py
  src/pyFAI/test/test_bispev.py
  src/pyFAI/test/test_massif.py
  src/pyFAI/utils/logging_utils.py
  src/pyFAI/utils/mathutil.py
Labels: ready to merge, easy

#2364 Update changelog.rst in prevision of the release
  doc/source/changelog.rst
  version.py
Labels: enhancement, work in progress, improvement needed, doc, easy

#2379 new tests to check the orientations
  doc/source/changelog.rst
  src/pyFAI/test/test_fiber_integrator.py
Labels: ready to merge

#2381 Use unit.name as key cache
  src/pyFAI/geometry/core.py
  src/pyFAI/units.py
Labels: ready to merge

#2388 use `unit.space` in diffmap.py
  src/pyFAI/diffmap.py
Labels: ready to merge, easy

#2386 update CI
  .github/workflows/python-package.yml
  ci/appveyor.yml
Labels: ready to merge, packaging

#2403 cybersecurity
  src/pyFAI/app/benchmark.py
  src/pyFAI/app/calib.py
  src/pyFAI/app/calib2.py
  src/pyFAI/app/integrate.py
  src/pyFAI/app/mx_calibrate.py
  src/pyFAI/app/recalib.py
Labels: enhancement

#2401 Update windows.rst
  doc/source/operations/windows.rst
Labels: ready to merge, doc

#2400 Update linux.rst
  doc/source/operations/linux.rst
Labels: ready to merge, doc

#2399 Update macosx.rst
  doc/source/operations/macosx.rst
Labels: ready to merge, doc

#2398 Update index.rst
  doc/source/operations/index.rst
Labels: ready to merge, doc

#2395 equivalence azimuth and radial units
  src/pyFAI/integrator/azimuthal.py
  src/pyFAI/test/test_azimuthal_integrator.py
  src/pyFAI/utils/mathutil.py
Labels: ready to merge

#2385 Quality of geometry fit
  src/pyFAI/test/test_utils_mathutil.py
  src/pyFAI/utils/mathutil.py
Labels: enhancement, ready to merge

#2380 Support for grazing-incidence exit angles and polar angle
  sandbox/test_gi_different_units.py
  src/pyFAI/integrator/fiber.py
  src/pyFAI/units.py
Labels: ready to merge

#2331 Compatibility between FiberIntegrator and MultiGeometry
  src/pyFAI/multi_geometry.py
Labels: ready to merge

#2410 API for exit and polar angles
  src/pyFAI/integrator/fiber.py
Labels: enhancement, ready to merge

#2411 changelog: fiber features
  doc/source/changelog.rst
Labels: ready to merge

#2412 Doc 2025.01
  .github/workflows/release.yml
  doc/source/changelog.rst
  doc/source/coverage.rst
  pyproject.toml
Labels: ready to merge, doc
