Repository silx-kit/pyFAI, pull requests merged in 2025-03, with the labels that each got.

#2461 parsing fiber units with warning
  src/pyFAI/integrator/fiber.py
  src/pyFAI/units.py
Labels: ready to merge

#2462 nbpt_azim null
  src/pyFAI/worker.py
Labels: ready to merge

#2464 Allow MultiGeometry to guess radial & azimuthal ranges when detectors are different shapes
  src/pyFAI/multi_geometry.py
Labels: ready to merge

#2463 Provide a more explicit exception
  src/pyFAI/integrator/azimuthal.py
  src/pyFAI/test/test_azimuthal_integrator.py
Labels: enhancement, ready to merge, packaging

#2465 dynamic range in benchmark
  src/pyFAI/benchmark/__init__.py
Labels: ready to merge

#2468 Fakedata background
  src/pyFAI/calibrant.py
Labels: ready to merge

#2467 automatic dynamic mask for Dectris detetors
  src/pyFAI/detectors/_common.py
  src/pyFAI/ext/CSR_common.pxi
  src/pyFAI/integrator/azimuthal.py
  src/pyFAI/test/test_azimuthal_integrator.py
  src/pyFAI/test/test_csr.py
  src/pyFAI/test/test_geometry.py
  src/pyFAI/test/test_integrate.py
  src/pyFAI/test/test_mask.py
  src/pyFAI/test/test_utils_mathutil.py
Labels: ready to merge

#2479 [Worker] parse_integration_method
  src/pyFAI/worker.py
Labels: ready to merge

#2489 remove assert from production code
  src/pyFAI/detectors/_common.py
  src/pyFAI/detectors/_hexagonal.py
  src/pyFAI/distortion.py
  src/pyFAI/engines/CSC_engine.py
  src/pyFAI/engines/CSR_engine.py
  src/pyFAI/engines/histogram_engine.py
  src/pyFAI/engines/preproc.py
  src/pyFAI/geometry/core.py
  src/pyFAI/geometry/fit2d.py
  src/pyFAI/geometryRefinement.py
  src/pyFAI/goniometer.py
  src/pyFAI/gui/ApplicationContext.py
  src/pyFAI/gui/CalibrationContext.py
  src/pyFAI/gui/CalibrationWindow.py
  src/pyFAI/gui/cli_calibration.py
  src/pyFAI/gui/dialog/DetectorSelectorDialog.py
  src/pyFAI/gui/dialog/GeometryDialog.py
  src/pyFAI/gui/dialog/OpenClDeviceDialog.py
  src/pyFAI/gui/helper/RingCalibration.py
  src/pyFAI/gui/helper/RingExtractor.py
  src/pyFAI/gui/helper/SynchronizeRawView.py
  src/pyFAI/gui/model/AbstractModel.py
  src/pyFAI/gui/model/ListModel.py
  src/pyFAI/gui/model/PeakModel.py
  src/pyFAI/gui/mpl_calib.py
  src/pyFAI/gui/peak_picker.py
  src/pyFAI/gui/pilx/utils.py
  src/pyFAI/gui/pilx/widgets/DiffractionImagePlotWidget.py
  src/pyFAI/gui/pilx/widgets/IntegratedPatternPlotWidget.py
  src/pyFAI/gui/pilx/widgets/MapPlotWidget.py
  src/pyFAI/gui/tasks/PeakPickingTask.py
  src/pyFAI/gui/utils/imageutils.py
  src/pyFAI/gui/widgets/FileEdit.py
  src/pyFAI/gui/widgets/GeometryLabel.py
  src/pyFAI/gui/widgets/GeometryTabs.py
  src/pyFAI/gui/widgets/MethodLabel.py
  src/pyFAI/integrator/azimuthal.py
  src/pyFAI/integrator/common.py
  src/pyFAI/io/__init__.py
  src/pyFAI/io/ponifile.py
  src/pyFAI/io/sparse_frame.py
  src/pyFAI/io/spots.py
  src/pyFAI/method_registry.py
  src/pyFAI/opencl/OCLFullSplit.py
  src/pyFAI/opencl/peak_finder.py
  src/pyFAI/opencl/preproc.py
  src/pyFAI/opencl/sort.py
  src/pyFAI/parallax.py
  src/pyFAI/test/test_goniometer.py
  src/pyFAI/test/test_pickle.py
  src/pyFAI/test/test_sparse.py
  src/pyFAI/test/test_utils.py
  src/pyFAI/test/utilstest.py
  src/pyFAI/utils/bayes.py
  src/pyFAI/utils/grid.py
  src/pyFAI/utils/logging_utils.py
  src/pyFAI/utils/mask_utils.py
  src/pyFAI/utils/mathutil.py
Labels: ready to merge

#2490 Debian13 packaging files
  build-deb.sh
  package/debian13/changelog
  package/debian13/control
  package/debian13/copyright
  package/debian13/gbp.conf
  package/debian13/gitlab-ci.yml
  package/debian13/patches/0001-fix-desktop-files.patch
  package/debian13/patches/series
  package/debian13/py3dist-overrides
  package/debian13/python-pyfai-doc.doc-base
  package/debian13/rules
  package/debian13/source/format
  package/debian13/tests/control
  package/debian13/tests/gui
  package/debian13/tests/no-opencl
  package/debian13/tests/opencl
  package/debian13/upstream/metadata
  package/debian13/upstream/signing-key.asc
  package/debian13/upstream/upstream/metadata
  package/debian13/watch
  src/pyFAI/method_registry.py
Labels: ready to merge, packaging
